"""Add name, bio, and profile_photo columns to User table

Revision ID: 1a1bee0760d2
Revises: 2185686e4576
Create Date: 2025-01-20 16:39:56.442331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1bee0760d2'
down_revision = '2185686e4576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('bio')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
